# version: "3"

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-docker-container
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel,volkovlabs-variable-panel,yesoreyeram-infinity-datasource,marcusolsson-json-datasource,grafana-clock-panel,volkovlabs-echarts-panel
      # - GF_AUTH_URL = http://localhost:3000
    ports:
      - "3001:3001"
    volumes: # :ro -> 읽기 전용
      - "storage:/var/lib/grafana"
      - "./datasources:/etc/grafana/provisioning/datasources/"
      - "./dashboards:/etc/grafana/provisioning/dashboards/"
      - "./dashboards:/var/lib/grafana/dashboards"
      # Setting Change
      - ./grafana.ini:/etc/grafana/grafana.ini
      # Icon Change
      - ./img/grafana_icon.svg:/usr/share/grafana/public/img/grafana_icon.svg
      # Favicon Change
      - ./img/fav32.png:/usr/share/grafana/public/img/fav32.png

volumes:
  storage: {}
