version: "3"

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana-compose-test
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel,volkovlabs-variable-panel,yesoreyeram-infinity-datasource,marcusolsson-json-datasource,grafana-clock-panel
    ports:
      - "3000:3000"
    volumes:
      - "grafana_storage:/var/lib/grafana"
volumes:
  grafana_storage: {}
